export const API_BASE_URL = "https://api.themoviedb.org/3/";
export const API_TOKEN =
  "eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIzZWM3MmY1MDg1NjgzNDUyYmI0NGFiNGIzYTg1NTc1NyIsIm5iZiI6MTczNDg0NjQ3Mi4wOTEsInN1YiI6IjY3NjdhODA4NTJhYjEyZGZlYTVlMzQwMyIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.yB9dGRDg01_898gY7KzvXFX3xgDzzriz0yetk-To_n4";
